### ISSUE TITLE
Argument for re-run only the tests failing

### ISSUE THREAD

**Issue by aislanmaia** [bahmutov/cypress-repeat#13]
Would be great for our CI/CD only re-run the failing ones. We can identify more easily the flaky tests and get reduced the time consumed by the ci machine..

**Comment by bahmutov** [comment]
Yes, but that is hard to implement externally, plus it already exists: the Test Retries https://docs.cypress.io/guides/guides/test-retries :)

**Comment by abhidp** [comment]
hi @bahmutov , 
Please show us a way on how to rerun only failed specs. 
Currently, if only 1 spec fails out of 100 specs, `cypress-repeat` reruns the entire 100 spec suite. 

Rerunning only failed specs will save us a lot of build time and money. 
Thanks.
