### ISSUE TITLE
Cypress-repeat ends with success despite of failures during tests

### ISSUE THREAD

**Issue by szymon-kellton** [bahmutov/cypress-repeat#49]
<img width="852" alt="Screenshot 2023-09-04 at 13 40 43" src="https://github.com/bahmutov/cypress-repeat/assets/130459593/f3e91d8e-cee8-4856-a77e-ab998c1ed373">

cypress-repeat ends with success despite of failures during tests

Cypress version 13.1.0

**Comment by alexprudhomme** [comment]
<img width="1030" alt="image" src="https://github.com/bahmutov/cypress-repeat/assets/78121423/effa0140-7684-4fc8-a46d-3fa090347b15">

Having the same issue with cypress 13.1
